{% set version = "2.7.2" %}

package:
  name: python-dateutil
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/python-dateutil/python-dateutil-{{ version }}.tar.gz
  sha256: 9d8074be4c993fbe4947878ce593052f71dac82932a677d49194d8ce9778002e

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - setuptools_scm
  run:
    - python
    - six >=1.5

test:
  imports:
    - dateutil
    - dateutil.rrule

about:
  home: https://dateutil.readthedocs.org/
  license: BSD 3 Clause
  license_file: LICENSE
  summary: 'Extensions to the standard Python datetime module.'
  description: |
    The dateutil module provides powerful extensions to the standard datetime
    module, available in Python.
  doc_url: https://dateutil.readthedocs.org/en/latest/
  dev_url: https://github.com/dateutil/dateutil/
  doc_source_url: https://github.com/dateutil/dateutil/blob/master/docs/index.rst

extra:
  recipe-maintainers:
    - msarahan
    - ocefpaf
