{% set version="2.7.0" %}

package:
  name: python-dateutil
  version: {{ version }}

source:
  fn: python-dateutil-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/python-dateutil/python-dateutil-{{ version }}.tar.gz
  sha256: 8f95bb7e6edbb2456a51a1fb58c8dca942024b4f5844cae62c90aa88afe6e300

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
    - setuptools_scm
  run:
    - python
    - six >=1.5

test:
  imports:
    - dateutil
    - dateutil.rrule
    - dateutil.parser
    - dateutil.tz
    - dateutil.zoneinfo

about:
  home: https://dateutil.readthedocs.org/
  license: BSD 3-clause
  license_file: LICENSE
  summary: 'Extensions to the standard Python datetime module.'
  description: |
    The dateutil module provides powerful extensions to the standard datetime
    module, available in Python.
  doc_url: https://dateutil.readthedocs.org/en/latest/
  dev_url: https://github.com/dateutil/dateutil/
  doc_source_url: https://github.com/dateutil/dateutil/blob/master/docs/index.rst

extra:
  recipe-maintainers:
    - msarahan
    - ocefpaf
