{% set version="2.5.3" %}

package:
  name: python-dateutil
  version: {{ version }}

source:
  fn: python-dateutil-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/python-dateutil/python-dateutil-{{ version }}.tar.gz
  sha256: 1408fdb07c6a1fa9997567ce3fcee6a337b39a503d80699e0f213de4aa4b32ed

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - six
  run:
    - python
    - six

test:
  imports:
    - dateutil
    - dateutil.rrule

about:
  home: https://dateutil.readthedocs.org/
  license: BSD 3-clause
  license_file: LICENSE
  summary: Extensions to the standard Python datetime module
  description: |
    The dateutil module provides powerful extensions to the standard datetime
    module, available in Python.
  doc_url: https://dateutil.readthedocs.org/en/latest/
  dev_url: https://github.com/dateutil/dateutil/

extra:
  recipe-maintainers:
    - msarahan
    - ocefpaf
