# NOT FOR DEFAULTS.
package:
  name: python-dateutil
  # The Python packaging ecosystem and conda support what's called a local version identifier (https://peps.python.org/pep-0440/#local-version-identifiers). 
  # So instead of 2.8.3a1 use 2.8.3+snowflake<n>
  version: 2.8.3+snowflake1

source:
  url: https://pypi.io/packages/source/p/python-dateutil/python-dateutil-2.8.2.tar.gz
  sha256: 0123cacc1627ae19ddf3c27a5de5bd67ee4586fbdd6440d9748f8abb483d3e86
  patches:
    - new_tzfile.patch
    - fix_version.patch

build:
  # Bump the build number to ensure that 2.8.3+snowflake1 is greater than 2.8.3a1
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - m2-patch  # [win]
    - patch     # [not win]
  host:
    - python
    - pip
    - wheel
    - setuptools
    # Disable setuptools_scm because we patch the package version vy 'fix_version.patch'
    #- setuptools_scm
  run:
    - python
    - six >=1.5

test:
  # to satisfy anaconda-linter imports and pip check are placed inside run_test.py
  requires:
    - pip
    - importlib_metadata

about:
  home: https://dateutil.readthedocs.org/
  license: BSD-3-Clause and Apache-2.0
  license_family: BSD
  license_file: LICENSE
  summary: Extensions to the standard Python datetime module
  description: |
    The dateutil module provides powerful extensions to the standard datetime
    module, available in Python.
  doc_url: https://dateutil.readthedocs.io/
  dev_url: https://github.com/dateutil/dateutil/

extra:
  recipe-maintainers:
    - pganssle
    - msarahan
    - ocefpaf
