package:
  name: python-dateutil
  version: 2.9.0post0

source:
  url: https://pypi.io/packages/source/p/python-dateutil/python-dateutil-2.8.2.tar.gz
  sha256: 0123cacc1627ae19ddf3c27a5de5bd67ee4586fbdd6440d9748f8abb483d3e86

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
    - setuptools_scm
  run:
    - python
    - six >=1.5

test:
  # to satisfy anaconda-linter imports and pip check are placed inside run_test.py
  requires:
    - pip
    - importlib_metadata

about:
  home: https://dateutil.readthedocs.io/
  license: BSD-3-Clause and Apache-2.0
  license_family: BSD
  license_file: LICENSE
  summary: Extensions to the standard Python datetime module
  description: |
    The dateutil module provides powerful extensions to the standard datetime
    module, available in Python.
  doc_url: https://dateutil.readthedocs.io/
  dev_url: https://github.com/dateutil/dateutil/

extra:
  recipe-maintainers:
    - pganssle
    - msarahan
    - ocefpaf
