# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "NmhdONCanS1K1xW0eL/UzQ2Gn4E+K8R6GmxRiGdzPJwKa5qVzVk8+yt1LIU338klSaeHBmuhYtzROAimp1NQ0AMJRn9ja7EdAQxoZVkMTHVZ2sfUe51A5HbIUsuUFVKnTtQIGcIE3lUGgva0HwMTf38ssU50OKlU0biHHY3mG1pgos22byT37Bt3Pxozpno0QppLEoVD0ksa0kzeM8rOtoa11ftbDD/LLFMQocAJ5egi3x4aArBuCk3qJkVWRG8qdf2ymu5GcT7LqhxWZk6Zsr9CkMG1zeLfkl4Mpqe33bVtNhkCTSb318C//aatuQ1PehQtL8/MWAXQAaUgo0ZZY2N22Rc96QWbNJ8IgelE7j5w+G/19vKHG46JtI6yZJj50XLWc/JK+p2vZAxGNLsoJvIA08wRxa62eT7KXPHIcy2JQP6fgWvytcjvZQzgMt/zr3QBgaCo07LiWQkyIYUNYLtl6xxAY8N5oyTg5or8uWj9e2RV8vOx5i1+zu+Us8sBBuqdqkIZqtOZLyhgG0dKsK/VcxMiXQe1aG48PVBw/9hz4huXfacQxnnRd1eYYZMcryUIw9G98v/OhMzIq9aPmK9eumABz30Ly4iE3AxfwQcbPERAQLxM7LAbhkq5EE5w7RGa4C/V/c803S3h2nMqOrjr1MV6+DPTmVGgKJl8dzs="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
