travis:
  secure:
    BINSTAR_TOKEN: Lv/Xlid4MD/UM1CKEeQNz+ZqS+mRLSwAOxOcEE0aYy5s6QUQXbKHZNZ3/NTWZT9/AEqrQQgp1PEGt4S0dNG6DsEh1qVcUZ1cfw/nEuABnzAPwBP5TmTrWC+lMKmoUcQRqwFM6B3eqAGN2xMlHOyKocnYx3Ubs9PFgWWFA9EDLIscJoL7nbmIT2XE7moZIr4lU0tZ5jn6zdyTU7DB26Kf9Q98tezQ4ASr1CmMva3Px8TiRj5Tw5zHmuO8C++exb6f/9maf1wSeaPt9sdUGslTRostH3NUOlBmURftbuJEHtN/0Zb2e6QNJUpR0dKRZ8aHgEWRhE15g47QzzEuidm3SwXrlPBqteXSEgzOn+e4U3Z6liEyrLcRS+9NnXnBlY6U7+2ojxfboCy649QsAv59D5BJhL9ye3K2A1IBkC3cMrKLtfX2yOroYmSoD62euwjqooP3mDdK//P5/vV3MLmW6vc5zFQ1kdA7ridvpQNKR6s1owi2yCpqK/8kh61zhnOvmRm7sHG5/pzFyD4QT8cSvY9ibihpyU6m60eWyuyAe+c8AbcTn7O3XnlUu1zZnAQdfBZaMTEI0diD+g6QoFtJFrPFa9Gn/xYlR40iZbSTTENt/IlOtn+Pj0mW05G2ETFl0x+Mi4MWyTtDxzoQTIGSUYx6eYvXZIgmiN2Pa5t6q38=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
